name: Build and upload to PyPI

on:
    pull_request:
      branches:
        - "package-*"
    push:
      branches:
        - "package-*"
      tags:
        - "package-*"
    release:
        types:
            - published

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}"
  cancel-in-progress: true


defaults:
  run:
    shell: bash -l {0}


jobs:
  build_wheels:
    if: github.repository == 'Becksteinlab/zarrtraj'
    name: Build wheels
    runs-on: ${{ matrix.buildplat[0] }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [ubuntu-22.04, manylinux_x86_64, x86_64]
          - [macos-11, macosx_*, x86_64]
          - [windows-2019, win_amd64, AMD64]
          - [macos-14, macosx_*, arm64]
        python: ["cp310", "cp311", "cp312"]
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          CIBW_ARCHS: ${{ matrix.buildplat[2] }}
          CIBW_BUILD_VERBOSITY: 1

      - name: upload artifacts
        if: |
            (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/package')) ||
            (github.event_name == 'release' && github.event.action == 'published')
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    if: github.repository == 'Becksteinlab/zarrtraj'
    name: build package source distribution
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - name: upload artifacts
        if: |
            (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/package')) ||
            (github.event_name == 'release' && github.event.action == 'published')
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.tar.gz
          retention-days: 7

  upload_testpypi_zarrtraj:
    if: github.repository == 'Becksteinlab/zarrtraj' &&
        (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/package'))
    name: testpypi_upload_zarrtraj
    environment:
      name: publisher
      url: https://test.pypi.org/p/zarrtraj
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: upload_source_and_wheels
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/
 
  upload_pypi_zarrtraj:
    if: | 
      github.repository == 'Becksteinlab/zarrtraj' &&
      (github.event_name == 'release' && github.event.action == 'published')
    name: pypi_upload_zarrtraj
    environment:
      name: publisher
      url: https://pypi.org/p/zarrtraj
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: upload_source_and_wheels
        uses: pypa/gh-action-pypi-publish@v1.9.0
