name: Build and upload to PyPI

on:
    pull_request:
      branches:
        - "package-*"
    push:
      branches:
        - "package-*"
      tags:
        - "v*"
    release:
        types:
            - published

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}"
  cancel-in-progress: true


defaults:
  run:
    shell: bash -l {0}


jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Build wheel
        run: |
          pip wheel . -w wheelhouse/
      
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-whl
          path: ./wheelhouse/*.whl

  build_sdist:
    name: build package source distribution
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - name: Print directory contents
        run: |
          echo "Contents of the dist directory:"
          ls -l dist

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: ./dist/*.tar.gz

  upload_testpypi_zarrtraj:
    name: testpypi_upload_zarrtraj
    environment:
      name: publisher
      url: https://test.pypi.org/p/zarrtraj
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]
    steps:

      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Print directory contents
        run: |
          echo "Contents of the dist directory:"
          ls -l dist

      - name: upload_source_and_wheels
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/
 
  upload_pypi_zarrtraj:
    name: pypi_upload_zarrtraj
    environment:
      name: publisher
      url: https://pypi.org/p/zarrtraj
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: upload_source_and_wheels
        uses: pypa/gh-action-pypi-publish@v1.9.0
